male_nouns = [
    ('jour', 'day'),
    ('jus', 'juice'),
    ('passeport', 'passport'),
    ('cafe', 'coffee'),
    ('cafe', 'coffee shop'),
    ('the', 'tea'),
    ('lait', 'milk'),
    ('sucre', 'sugar'),
    ('croissant', 'croissant'),
    ('hotel', 'hotel'),
    ('restaurant', 'restaurant'),
    ('batiment', 'building'),
    ('bureau', 'office'),
    ('magasin', 'store'),
    ('probleme', 'problem'),
    ('liquide', 'cash'),
    ('musee', 'museum'),
    ('jambon', 'ham'),
    ('fromage', 'cheese'),
    ('sandwich', 'sandwich'),
    ('thon', 'tuna'),
    ('pate', 'pate'),
    ('chocolat', 'chocolate'),
    ('homme', 'man'),
    ('mari', 'husband'),
    ('ami', 'friend'),
    ('nom', 'name'),
    ('prenom', 'first name'),
    ('vin', 'wine'),
    ('portable', 'cellphone'),
    ('internet', 'internet'),
    ('dentifrice', 'toothpaste'),
    ('shampooing', 'shampoo'),
    ('savon', 'soap'),
    ('centre', 'center'),
    ('glacon', 'ice cube'),
    ('euro', 'euro'),
    ('travail', 'work'),
    ('argent', 'money'),
    ('numero', 'number'),
    ('arret', 'stop'),
    ('taxi', 'taxi'),
    ('metro', 'metro'),
    ('bus', 'bus'),
    ('train', 'train'),
    ('avion', 'plane'),
    ('billet', 'ticket'),
    ('ticket', 'ticket'),
    ('aeroport', 'airport'),
    ('matin', 'morning'),
    ('apres-midi', 'afternoon'),
    ('soir', 'evening'),
    ('marche', 'market'),
    ('supermarche', 'supermarket'),
    ('theatre', 'theater'),
    ('cinema', 'cinema'),
    ('parc', 'park'),
    ('recu', 'receipt')
]

female_nouns = [
    ('nuit', 'night'),
    ('table', 'table'),
    ('carte', 'card'),
    ('addition', 'bill'),
    ('moutarde', 'mustard'),
    ('crepe', 'crepe'),
    ('omelette', 'omelette'),
    ('chantilly', 'whipped cream'),
    ('famille', 'family'),
    ('femme', 'woman'),
    ('amie', 'friend(f)'),
    ('valise', 'suitcase'),
    ('orange', 'orange'),
    ('maison', 'house'),
    ('biere', 'beer'),
    ('eau', 'water'),
    ('puce', 'chip'),
    ('patisserie', 'pastry'),
    ('patisserie', 'pastry shop'),
    ('creme', 'cream'),
    ('brosse', 'brush'),
    ('dent', 'tooth'),
    ('pharmacie', 'pharmacy'),
    ('personne', 'person'),
    ('vacance', 'holiday'),
    ('langue', 'language'),
    ('banque', 'bank'),
    ('heure', 'hour'),
    ('ligne', 'line'),
    ('station', 'station'),
    ('gare', 'train station'),
    ('place', 'plaza'),
    ('voiture', 'car'),
    ('avenue', 'avenue'),
    ('rue', 'street'),
    ('entree', 'entrance'),
    ('sortie', 'exit')
]

nogender_nouns = [
    'chef',
    'collegue',
]

possessives = [
        ('my', 'mon', 'ma', 'mes'),
        ('our', 'notre', 'notre', 'nos'),
        ('his', 'son', 'sa', 'ses'),
        ('her', 'son', 'sa', 'ses'),
        ('their', 'leur', 'leur', 'leurs'),
        ('your', 'votre', 'votre', 'vos'),
        ]
vowels = ['a', 'e', 'i', 'o', 'u']

irregular_verbs = [
    ('etre', 'to be'),
    ('avoir', 'to have'),
    ('vouloire', 'to want'),
    ('pouvoir', 'to be able to/can'),
    ('aller', 'to go'),
    ('venir', 'to come'),
    ('boire', 'to drink'),
    ('voir', 'to see'),
    ('savoir', 'to know'),
    ('comprendre', 'to understand'),
    ('partir', 'to leave'),
]

regular_verbs = [
    ('changer', 'to change', 'chang'),
    ('voyager', 'to travel', 'voyag'),
    ('manger', 'to eat', 'mang'),
    ('acheter', 'to buy', 'achet'),
    ('parler', 'to talk', 'parl'),
    ('regarder', 'to watch', 'regard'),
    ('donner', 'to give', 'donn'),
    ('retirer', 'to withdraw', 'retir'),
    ('payer', 'to pay', 'pay'),
    ('arriver', 'to arrive', 'arriv'),
    ('repeter', 'to repeat', 'repet')
]

pronouns = [
    ('je', 'i'),
    ('nous', 'we'),
    ('vous', 'you'),
    ('tu', 'you(i)'),
    ('il', 'he'),
    ('elle', 'she'),
    ('ils', 'they'),
    ('elles', 'they(f)'),
]


dictionary = {
    'etre': {
        'je': 'suis',
        'nous': 'sommes',
        'vous': 'etes',
        'tu': 'es',
        'il': 'est',
        'elle': 'est',
        'ils': 'sont',
        'elles': 'sont',
    },
    'avoir': {
        'je': 'ai',
        'nous': 'avons',
        'vous': 'avez',
        'tu': 'as',
        'il': 'a',
        'elle': 'a',
        'ils': 'ont',
        'elles': 'ont',
    },
    'aller': {
        'je':    'vais',
        'tu':    'vas',
        'nous':  'allons',
        'vous':  'allez',
        'il':    'va',
        'elle':  'va',
        'ils':   'vont',
        'elles': 'vont',
    },
    'vouloir': {
        'je':    'veux',
        'tu':    'veux',
        'nous':  'voulons',
        'vous':  'voulez',
        'il':    'veut',
        'elle':  'veut',
        'ils':   'veulent',
        'elles': 'veulent',
    },
    'pouvoir': {
        'je':     'peux',
        'tu':     'peux',
        'nous':   'pouvons',
        'vous':   'pouvez',
        'il' :    'peut',
        'elle' :  'peut',
        'ils' :   'peuvent',
        'elles' : 'peuvent',
    },
    'savoir': {
        'je':     'sais',
        'tu':     'sais',
        'nous':   'savons',
        'vous':   'savez',
        'il' :    'sait',
        'elle' :  'sait',
        'ils' :   'savent',
        'elles' : 'savent',
        },
    'comprendre': {
        'je' :    'comprends',
        'tu':     'comprends',
        'vous':   'comprendez',
        'nous':   'comprendons',
        'il':     'comprend',
        'elle':   'comprend',
        'ils' :   'comprendent',
        'elles' : 'comprendent'
        },
}

for verb in regular_verbs:
    suffix = verb[2]

    ons = 'ons'
    if suffix[-1] == 'g':
        ons = 'eons'

    d = {
        'je':    suffix + 'e',
        'tu':    suffix + 'es',
        'il':    suffix + 'e',
        'elle':  suffix + 'e',
        'nous':  suffix + ons,
        'vous':  suffix + 'ez',
        'ils':   suffix + 'ent',
        'elles': suffix + 'ent'
    }
    dictionary[verb[0]] = d
